'use client'

import React, { createContext, useContext, useState, useEffect } from 'react'

type Language = 'TH' | 'EN'

interface LanguageContextType {
    lang: Language
    setLang: (lang: Language) => void
    t: (key: string) => string
}

const translations = {
    TH: {
        dashboard: 'แดชบอร์ด',
        rooms: 'ห้องพัก',
        reservations: 'การจอง',
        housekeeping: 'งานแม่บ้าน',
        maintenance: 'การแจ้งซ่อม',
        reports: 'รายงาน',
        pos: 'จุดขายสินค้า',
        finance: 'การเงิน',
        settings: 'ตั้งค่า',
        logout: 'ออกจากระบบ',
        login: 'เข้าสู่ระบบ',
        username: 'ชื่อผู้ใช้',
        password: 'รหัสผ่าน',

        // Reports
        monthlyRevenue: 'ยอดรายได้รายเดือน',
        shiftHistory: 'ประวัติกะการทำงาน',
        occupancyMetrics: 'สถิติการเข้าพัก',
        housekeepingStats: 'สถิติงานแม่บ้าน',
        stayOccupancy: 'อัตราการเข้าพัก',
        reservedLoad: 'อัตราการจอง',
        occupied: 'เข้าพักอยู่',
        reserved: 'มีการจอง',
        vacantDirty: 'ห้องว่าง (ต้องทำความสะอาด)',
        vacantClean: 'ห้องว่าง (พร้อมขาย)',
        expectedArrivals: 'รายการเช็คอินวันนี้',
        expectedDepartures: 'รายการเช็คเอาท์วันนี้',
        roomStatusDetail: 'รายละเอียดสถานะห้องพัก',
        outstandingBalances: 'รายการค้างชำระ',
        totalSales: 'ยอดขายรวม',
        checkIn: 'เข้าพัก',
        checkOut: 'ออก',
        room: 'ห้อง',
        noShiftHistory: 'ไม่พบประวัติกะ',
        noArrivals: 'ไม่มีการเช็คอินวันนี้',
        noDepartures: 'ไม่มีการเช็คเอาท์วันนี้',
        noOutstanding: 'ไม่มีรายการค้างชำระ',

        // Dashboard
        hotelOverview: 'ภาพรวมโรงแรม',
        dashboardDesc: 'สถานะปัจจุบันและการดำเนินงาน',
        todaysOccupancy: 'อัตราเข้าพักวันนี้',
        maintenanceCount: 'รายการแจ้งซ่อม',
        needHelp: 'ต้องการความช่วยเหลือ?',
        systemRunning: 'ระบบทำงานปกติ ตรวจสอบประวัติได้ที่หน้าตั้งค่า',
        notifications: 'การแจ้งเตือน',
        allGood: 'ปกติ',
        systemSmooth: 'ระบบทำงานได้ดี ไม่มีรายการต้องดำเนินการทันที',
        housekeepingNeeded: 'ต้องการคนทำความสะอาด',
        nextOldData: 'ดูข้อมูลย้อนหลัง',

        // Rooms
        floor: 'ชั้น',
        updateRoomStatus: 'อัปเดตสถานะห้อง',
        capacity: 'ความจุ',
        outOfOrder: 'ปิดซ่อม',
        inspecting: 'อยู่ระหว่างตรวจห้อง',
        cleaning: 'อยู่ระหว่างทำความสะอาด',

        // Reservations
        newBooking: 'จองใหม่',
        guestName: 'ชื่อลูกค้า',
        stayDates: 'วันที่เข้าพัก',
        nights: 'คืน',
        status: 'สถานะ',
        actions: 'ดำเนินการ',
        checkInDate: 'วันที่เช็คอิน',
        checkOutDate: 'วันที่เช็คเอาท์',
        bookingNo: 'รหัสการจอง',
        searchBooking: 'ค้นหารหัสจอง หรือชื่อลูกค้า...',
        noBookings: 'ไม่พบข้อมูลการจอง',
        cancel: 'ยกเลิก',
        completed: 'สำเร็จ',
        cancelled: 'ยกเลิกแล้ว',
        confirmed: 'ยืนยันแล้ว',
        checkedIn: 'เช็คอินแล้ว',
        checkedOut: 'เช็คเอาท์แล้ว',
        confirmStatus: 'ยืนยันการเปลี่ยนสถานะเป็น',

        // New Booking Modal
        bookingConfirmed: 'ยืนยันการจองสำเร็จ!',
        bookingSaved: 'ข้อมูลการจองของท่านถูกบันทึกเรียบร้อยแล้ว',
        source: 'ช่องทางการจอง',
        paymentMethod: 'วิธีการชำระเงิน',
        phone: 'เบอร์โทรศัพท์',
        roomType: 'ประเภทห้อง',
        roomNo: 'เลขห้อง',
        autoAssign: 'เลือกห้องอัตโนมัติ',
        ratePerNight: 'ราคาต่อคืน',
        adults: 'ผู้ใหญ่',
        children: 'เด็ก',
        addRoom: 'เพิ่มห้อง',
        selectType: 'เลือกประเภท',
        processing: 'กำลังดำเนินการ...',
        createBooking: 'สร้างการจอง',
        noRoomsSelected: 'ยังไม่ได้เลือกห้อง คลิก "เพิ่มห้อง" เพื่อเริ่ม',

        // Housekeeping
        dirtyRooms: 'ห้องที่ต้องทำความสะอาด',
        inProgress: 'กำลังทำความสะอาด',
        toInspect: 'รอตรวจสอบ',
        cleanReady: 'ห้องว่างพร้อมขาย',
        startCleaning: 'เริ่มทำความสะอาด',
        finishInspect: 'เสร็จสิ้นและรอตรวจ',
        markAsCleaned: 'ทำความสะอาดแล้ว',

        // Maintenance
        maintenanceTickets: 'รายการแจ้งซ่อม',
        reportIssue: 'แจ้งซ่อม',
        issueDescription: 'รายละเอียดปัญหา',
        priority: 'ระดับความสำคัญ',
        low: 'ปกติ (LOW)',
        medium: 'ด่วน (MEDIUM)',
        high: 'ด่วนที่สุด (HIGH)',
        startWork: 'เริ่มดำเนินการ',
        resolve: 'จบงาน',
        resolved: 'ซ่อมเสร็จแล้ว',
        reportNewIssue: 'สร้างรายการแจ้งซ่อมใหม่',
        describeProblem: 'ระบุปัญหาที่พบ...',
        selectRoom: 'เลือกห้องพัก',
        roomNumber: 'หมายเลขห้อง',
        noActiveMaintenanceTickets: 'ไม่มีรายการแจ้งซ่อมที่รอดำเนินการ',
        reported: 'แจ้งเมื่อ',
        issueReportedSuccessfully: 'บันทึกรายการแจ้งซ่อมสำเร็จ',
        failedToReportIssue: 'ไม่สามารถบันทึกรายการแจ้งซ่อมได้',
        ticketStatusUpdated: 'อัปเดตสถานะรายการแล้ว',
        failedToUpdateTicket: 'ไม่สามารถอัปเดตสถานะได้',
        errorUpdatingStatus: 'เกิดข้อผิดพลาดในการอัปเดตสถานะ',
        submitTicket: 'ส่งรายการแจ้งซ่อม',

        // POS
        currentOrder: 'รายการสั่งซื้อปัจจุบัน',
        emptyCart: 'ไม่มีสินค้าในระบบ',
        cash: 'เงินสด',
        qrPay: 'คิวอาร์พร้อมเพย์',
        closeShift: 'ปิดกะ / สรุปยอด',
        openShift: 'เปิดกะใหม่',
        startingCash: 'เงินทอนเริ่มต้น',
        posSales: 'ยอดขายหน้าบ้าน (POS)',
        cashSales: 'ยอดเงินสดในเก๊ะ',
        otherSales: 'ยอดโอน/บัตร (อื่นๆ)',
        printReport: 'พิมพ์รายงาน',
        totalDiscount: 'ส่วนลดทั้งหมด',
        saleAfterDisc: 'ยอดหลังยอดขายส่วนลด',
        payment: 'การชำระเงิน',
        totalBills: 'จำนวนบิลทั้งหมด',
        avgBill: 'ยอดเฉลี่ยต่อบิล',
        vat: 'ภาษีมูลค่าเพิ่ม (VAT)',
        serviceCharge: 'ค่าบริการ (Service Charge)',
        confirmClose: 'ยืนยันการปิดกะ',
        posLocked: 'ระบบการเงินถูกล็อค',
        posLockedDesc: 'กรุณาเปิดกะก่อนเริ่มใช้งานหน้า POS',
        activeShift: 'กะปัจจุบัน',
        posSection: '1. ยอดขาย POS',
        roomSection: '2. ยอดขายห้อง',
        cashFlowSection: '3. เงินสดเข้า-ออก',
        adminViewAllData: 'มุมมองผู้ดูแล (ข้อมูลทั้งหมด)',
        goToPosOpenShift: 'ไปที่หน้า POS เพื่อเปิดกะ',

        // Finance
        financeTransactions: 'รายการบันทึกการเงิน',
        financeDesc: 'ติดตามการเข้า-ออกของเงินสดระหว่างวัน',
        totalBalance: 'ยอดคงเหลือรวม',
        shiftBalance: 'ยอดคงเหลือประจำกะ',
        recordCashFlow: 'บันทึกรายรับ/รายจ่าย',
        income: 'รายรับ (เข้า)',
        expense: 'รายจ่าย (ออก)',
        category: 'ประเภทรายการ',
        pettyCash: 'เงินย่อย',
        refund: 'คืนมัดจำ',
        refundDeposit: 'คืนเงินมัดจำ',
        purchase: 'ซื้อของ/วัสดุอุปกรณ์',
        suppliesMarket: 'ซื้อของ/วัสดุอุปกรณ์',
        utility: 'ค่าน้ำ/ค่าไฟ',
        utilityBill: 'ค่าน้ำ/ค่าไฟ',
        other: 'อื่นๆ',
        amount: 'จำนวนเงิน (บาท)',
        amountPlaceholder: '0.00',
        description: 'รายละเอียด',
        descriptionPlaceholder: 'ระบุรายละเอียด...',
        reference: 'เลขอ้างอิง (ถ้ามี)',
        ref: 'อ้างอิง',
        referenceOptional: 'เลขอ้างอิง (ถ้ามี)',
        referencePlaceholder: 'รหัสการจอง หรือ เลขใบรับเงิน',
        recordTransaction: 'บันทึกรายการ',
        noTransactions: 'ไม่พบรายการเงิน',
        noTransactionsFound: 'ไม่พบข้อมูลรายการเงิน',
        date: 'วันที่',
        type: 'ประเภท',
        searchTransactionsRef: 'ค้นหารายการ, อ้างอิง...',

        // Settings
        systemConfiguration: 'ตั้งค่าระบบ',
        general: 'ทั่วไป',
        roomTypes: 'ประเภทห้อง',
        products: 'สินค้า POS',
        users: 'ผู้ใช้งาน',
        accessDenied: 'ปฏิเสธการเข้าถึง',
        noPermissionSettings: 'คุณไม่มีสิทธิ์เข้าถึงการตั้งค่าระบบ กรุณาติดต่อผู้ดูแลระบบ',
        hotelInformation: 'ข้อมูลโรงแรม',
        address: 'ที่อยู่',
        taxId: 'เลขประจำตัวผู้เสียภาษี',
        saveChanges: 'บันทึกการเปลี่ยนแปลง',
        settingsSaved: 'บันทึกการตั้งค่าเรียบร้อยแล้ว',
        failedToSave: 'ไม่สามารถบันทึกข้อมูลได้',
        manageRoomTypes: 'จัดการประเภทห้องพัก',
        addRoomType: 'เพิ่มประเภทห้องพัก',
        baseRate: 'ราคาเริ่มต้น',
        amenities: 'สิ่งอำนวยความสะดวก',
        areYouSure: 'คุณแน่ใจหรือไม่?',
        failedToDelete: 'ไม่สามารถลบข้อมูลได้ (ข้อมูลอาจถูกใช้งานอยู่)',
        manageUsers: 'จัดการผู้ใช้งาน',
        addUser: 'เพิ่มผู้ใช้งาน',
        role: 'ตำแหน่ง / สิทธิ์',
        reception: 'พนักงานต้อนรับ',
        admin: 'ผู้ดูแลระบบ',
        manageRooms: 'จัดการห้องพัก',
        addRoomSetting: 'เพิ่มห้องพัก',
        floorNumber: 'ชั้นที่',
        createRoom: 'สร้างห้องพัก',
        noRoomsOnFloor: 'ไม่มีห้องพักในชั้นนี้',
        manageProducts: 'จัดการสินค้า POS',
        addProduct: 'เพิ่มสินค้า',
        productName: 'ชื่อสินค้า',
        cost: 'ราคาทุน',
        stock: 'จำนวนคงเหลือ',
        barcode: 'บาร์โค้ด',
        saveProduct: 'บันทึกสินค้า',
        inStock: 'ชิ้นในสต็อก',
        edit: 'แก้ไข',
        delete: 'ลบ',
        confirmDeleteRoom: 'คุณแน่ใจหรือไม่ว่าต้องการลบห้องพักนี้?',
        failedToDeleteRoom: 'ไม่สามารถลบห้องพักได้',
        confirmDeleteProduct: 'คุณแน่ใจหรือไม่ว่าต้องการลบสินค้านี้?',
        confirmDeleteUser: 'คุณแน่ใจหรือไม่ว่าต้องการลบผู้ใช้นี้?',
        confirmDeleteType: 'คุณแน่ใจหรือไม่ว่าต้องการลบประเภทห้องนี้?',
    },
    EN: {
        hotelName: 'BookingNewyork Hotel',
        dashboard: 'Dashboard',
        rooms: 'Rooms',
        reservations: 'Reservations',
        housekeeping: 'Housekeeping',
        maintenance: 'Maintenance',
        reports: 'Reports',
        pos: 'POS',
        finance: 'Finance',
        settings: 'Settings',
        logout: 'Logout',
        login: 'Login',
        username: 'Username',
        password: 'Password',

        // Reports
        monthlyRevenue: 'Monthly Revenue Summary',
        shiftHistory: 'Shift History',
        occupancyMetrics: 'Occupancy Metrics',
        housekeepingStats: 'Housekeeping Stats',
        stayOccupancy: 'Stay Occupancy',
        reservedLoad: 'Reserved Load',
        occupied: 'Occupied',
        reserved: 'Reserved',
        vacantDirty: 'Vacant Dirty',
        vacantClean: 'Vacant Clean',
        expectedArrivals: 'Expected Arrivals',
        expectedDepartures: 'Expected Departures',
        roomStatusDetail: 'Room Status Detail',
        outstandingBalances: 'Outstanding Balances',
        totalSales: 'Total Sales',
        checkIn: 'Check-In',
        checkOut: 'Check-Out',
        room: 'Room',
        noShiftHistory: 'No shift history found.',
        noArrivals: 'No arrivals today',
        noDepartures: 'No departures today',
        noOutstanding: 'No outstanding balances',

        // Dashboard
        hotelOverview: 'Hotel Overview',
        dashboardDesc: 'Real-time status and operations summary',
        todaysOccupancy: "Today's Occupancy",
        maintenanceCount: 'Maintenance',
        needHelp: 'Need Help?',
        systemRunning: 'System is running normally. Check logs in Settings.',
        notifications: 'Notifications',
        allGood: 'All Good',
        systemSmooth: 'System is running smoothly. No immediate actions required.',
        housekeepingNeeded: 'Housekeeping Needed',
        nextOldData: 'Next: old data',

        // Rooms
        floor: 'Floor',
        updateRoomStatus: 'Update Status',
        capacity: 'Capacity',
        outOfOrder: 'Out of Order',
        inspecting: 'Inspecting',
        cleaning: 'Cleaning',

        // Reservations
        newBooking: 'New Booking',
        guestName: 'Guest',
        stayDates: 'Stay Dates',
        nights: 'Nights',
        status: 'Status',
        actions: 'Actions',
        checkInDate: 'Check-In Date',
        checkOutDate: 'Check-Out Date',
        bookingNo: 'Booking #',
        searchBooking: 'Search booking #, guest name...',
        noBookings: 'No bookings found',
        cancel: 'Cancel',
        completed: 'Completed',
        cancelled: 'Cancelled',
        confirmed: 'Confirmed',
        checkedIn: 'Checked-In',
        checkedOut: 'Checked-Out',
        confirmStatus: 'Are you sure you want to change status to',

        // New Booking Modal
        bookingConfirmed: 'Booking Confirmed!',
        bookingSaved: 'The reservation has been successfully saved.',
        source: 'Source (Channel)',
        paymentMethod: 'Payment Method',
        phone: 'Phone',
        roomType: 'Room Type',
        roomNo: 'Room No. (Optional)',
        autoAssign: 'Auto-Assign',
        ratePerNight: 'Rate (Night)',
        adults: 'Adults',
        children: 'Children',
        addRoom: 'Add Room',
        selectType: 'Select Type',
        processing: 'Processing...',
        createBooking: 'Create Booking',
        noRoomsSelected: 'No rooms selected. Click "Add Room" to start.',

        // Housekeeping
        dirtyRooms: 'Dirty Rooms',
        inProgress: 'In Progress',
        toInspect: 'To Inspect',
        cleanReady: 'Clean & Ready',
        startCleaning: 'Start Cleaning',
        finishInspect: 'Finish & Inspect',
        markAsCleaned: 'Mark as Cleaned',

        // Maintenance
        maintenanceTickets: 'Maintenance Tickets',
        reportIssue: 'Report Issue',
        issueDescription: 'Issue Description',
        priority: 'Priority',
        low: 'LOW',
        medium: 'MEDIUM',
        high: 'HIGH',
        startWork: 'Start Work',
        resolve: 'Resolve',
        resolved: 'Resolved',
        reportNewIssue: 'Report New Issue',
        describeProblem: 'Describe the problem...',
        selectRoom: 'Select Room',
        roomNumber: 'Room Number',
        noActiveMaintenanceTickets: 'No active maintenance tickets',
        reported: 'Reported',
        issueReportedSuccessfully: 'Issue reported successfully',
        failedToReportIssue: 'Failed to report issue',
        ticketStatusUpdated: 'Ticket status updated',
        failedToUpdateTicket: 'Failed to update ticket',
        errorUpdatingStatus: 'Error updating status',
        submitTicket: 'Submit Ticket',

        // POS
        currentOrder: 'Current Order',
        emptyCart: 'Cart is empty',
        cash: 'Cash',
        qrPay: 'QR Pay',
        closeShift: 'Close Shift / Summary',
        openShift: 'Open New Shift',
        startingCash: 'Starting Cash Float',
        posSales: 'POS Sales',
        cashSales: 'Net Cash in Drawer',
        otherSales: 'Total Other (Non-Cash)',
        printReport: 'Print Report',
        totalDiscount: 'Total Discount',
        saleAfterDisc: 'Sale After Disc.',
        payment: 'Payment',
        totalBills: 'Total Bills',
        avgBill: 'AVG / Bill',
        vat: 'VAT',
        serviceCharge: 'Service charge',
        confirmClose: 'Confirm Close',
        posLocked: 'Finance Locked',
        posLockedDesc: 'Please open a shift in the POS section first.',
        activeShift: 'Active Shift',
        posSection: '1. POS Sales',
        roomSection: '2. Room Revenue',
        cashFlowSection: '3. Cash In-Out',
        adminViewAllData: 'Admin View (All Data)',
        goToPosOpenShift: 'Go to POS to Open Shift',
        confirmCloseShiftMessage: 'Are you sure you want to end this shift? Ensure all cash is counted.',
        confirmPayment: 'Confirm Payment',
        confirmPaymentMessage: 'Process payment of the total amount via selected method?',
        searchProducts: 'Search products...',
        inStock: 'in stock',
        checkout: 'Checkout & Print',
        shift: 'Shift',
        cartIsEmpty: 'Cart is empty',
        total: 'Total',
        summary: 'Summary',
        shiftSummary: 'Shift Summary',
        shiftId: 'Shift ID',
        totalOrders: 'Total Orders',
        roomRevenue: 'Room Revenue',
        cashIn: 'Cash In',
        cashOut: 'Cash Out',
        netCashInDrawer: 'Net Cash in Drawer',
        totalOtherNonCash: 'Total Other (Non-Cash)',
        totalRevenue: 'Total Revenue',
        pleaseEnterStartingCash: 'Please enter starting cash',
        shiftOpenedSuccessfully: 'Shift opened successfully',
        failedToOpenShift: 'Failed to open shift',
        errorOpeningShift: 'Error opening shift',
        shiftClosedSuccessfully: 'Shift closed successfully',
        failedToCloseShift: 'Failed to close shift',
        pleaseOpenShiftFirst: 'Please open a shift first!',
        paymentSuccessful: 'Payment Successful!',
        paymentFailed: 'Payment Failed',
        errorProcessingPayment: 'Error processing payment',

        // Finance
        financeTransactions: 'Finance Transactions',
        financeDesc: 'Monitor and record cash flow during your shift.',
        totalBalance: 'Total Balance',
        shiftBalance: 'Current Shift Balance',
        recordCashFlow: 'Record Cash Flow',
        income: 'INCOME',
        expense: 'EXPENSE',
        category: 'Category',
        pettyCash: 'Petty Cash',
        refund: 'Refund Deposit',
        refundDeposit: 'Refund Deposit',
        purchase: 'Supplies/Market',
        suppliesMarket: 'Supplies/Market',
        utility: 'Utility/Bill',
        utilityBill: 'Utility/Bill',
        other: 'Other',
        amount: 'Amount',
        amountPlaceholder: '0.00',
        description: 'Description',
        descriptionPlaceholder: 'What is this for?',
        reference: 'Reference (Optional)',
        ref: 'Ref',
        referenceOptional: 'Reference (Optional)',
        referencePlaceholder: 'Booking # or Invoice #',
        recordTransaction: 'Record Transaction',
        noTransactions: 'No transactions found',
        noTransactionsFound: 'No transactions found',
        date: 'Date',
        type: 'Type',
        searchTransactionsRef: 'Search transactions, ref...',

        // Settings
        systemConfiguration: 'System Configuration',
        general: 'General',
        roomTypes: 'Room Types',
        products: 'Products',
        users: 'Users',
        accessDenied: 'Access Denied',
        noPermissionSettings: 'You do not have permission to access the system configuration. Please contact the administrator.',
        hotelInformation: 'Hotel Information',
        address: 'Address',
        taxId: 'Tax ID',
        saveChanges: 'Save Changes',
        settingsSaved: 'Settings saved!',
        failedToSave: 'Failed to save',
        manageRoomTypes: 'Manage Room Types',
        addRoomType: 'Add Room Type',
        baseRate: 'Base Rate',
        amenities: 'Amenities',
        areYouSure: 'Are you sure?',
        failedToDelete: 'Failed to delete (might be in use)',
        manageUsers: 'Manage Users',
        addUser: 'Add User',
        role: 'Role',
        reception: 'Reception',
        admin: 'Admin',
        manageRooms: 'Manage Rooms',
        addRoomSetting: 'Add Room',
        floorNumber: 'Floor Number',
        createRoom: 'Create Room',
        noRoomsOnFloor: 'No rooms on this floor',
        manageProducts: 'Manage Products',
        addProduct: 'Add Product',
        productName: 'Product Name',
        cost: 'Cost',
        stock: 'Stock',
        barcode: 'Barcode',
        saveProduct: 'Save Product',
        edit: 'Edit',
        delete: 'Delete',
        confirmDeleteRoom: 'Are you sure you want to delete this room?',
        failedToDeleteRoom: 'Failed to delete room',
        confirmDeleteProduct: 'Are you sure you want to delete this product?',
        confirmDeleteUser: 'Are you sure you want to delete this user?',
        confirmDeleteType: 'Are you sure you want to delete this room type?',
    }
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [lang, setLang] = useState<Language>('TH')

    const t = (key: string) => {
        return (translations[lang] as any)[key] || key
    }

    return (
        <LanguageContext.Provider value={{ lang, setLang, t }}>
            {children}
        </LanguageContext.Provider>
    )
}

export function useTranslation() {
    const context = useContext(LanguageContext)
    if (!context) throw new Error('useTranslation must be used within LanguageProvider')
    return context
}
